spring:
  datasource:
    username: mc
    password: Chudeptrai123
    url: jdbc:postgresql://polar-postgres:5432/polardb_catalog
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
      # Hibernate ddl auto (create, create-drop, validate, update)
    show-sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://host.docker.internal:8080/realms/PolarBookshop
logging:
  level:
    root: info

polar:
  greeting: Welcome to the local book catalog!

server:
  port: 9001